ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER PETRO IDENTIFIED BY petro';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN
            RAISE;
        END IF;
END;
/

GRANT CONNECT, RESOURCE TO PETRO;
GRANT CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE PROCEDURE TO PETRO;
GRANT UNLIMITED TABLESPACE TO PETRO;

ALTER SESSION SET CURRENT_SCHEMA = PETRO;

CREATE SEQUENCE PETRO.SEQ_PETRO_TODO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PETRO.SEQ_PETRO_AREA START WITH 1 INCREMENT BY 1;

CREATE TABLE PETRO.TB_PETRO_AREA (
    CD_AREA         NUMBER(10) NOT NULL,
    DS_NOME         VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_PETRO_AREA PRIMARY KEY (CD_AREA)
);

CREATE TABLE PETRO.TB_PETRO_TODO (
    CD_TAREFA       NUMBER(10) NOT NULL,
    CD_AREA         NUMBER(10),
    DS_TITULO       VARCHAR2(100) NOT NULL,
    DS_DESCRICAO    VARCHAR2(500),
    ST_STATUS       NUMBER(1) DEFAULT 0 NOT NULL,
    DT_VENCIMENTO   DATE NOT NULL,
    DT_CRIACAO      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ALTERACAO    TIMESTAMP,
    CONSTRAINT PK_PETRO_TODO PRIMARY KEY (CD_TAREFA),
    CONSTRAINT FK_PETRO_TODO_AREA FOREIGN KEY (CD_AREA) REFERENCES PETRO.TB_PETRO_AREA (CD_AREA),
    CONSTRAINT CK_PETRO_TODO_STATUS CHECK (ST_STATUS IN (0, 1, 2))
);

CREATE OR REPLACE TRIGGER PETRO.TRG_PETRO_TODO_BIU
BEFORE INSERT OR UPDATE ON PETRO.TB_PETRO_TODO
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CD_TAREFA IS NULL THEN
        SELECT PETRO.SEQ_PETRO_TODO.NEXTVAL INTO :NEW.CD_TAREFA FROM DUAL;
    END IF;

    :NEW.DT_ALTERACAO := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE PACKAGE PETRO.PKG_TODO_RULES AS
    PROCEDURE PRC_LIMPAR_CONCLUIDAS(P_DIAS IN NUMBER);
END PKG_TODO_RULES;
/

CREATE OR REPLACE PACKAGE BODY PETRO.PKG_TODO_RULES AS
    PROCEDURE PRC_LIMPAR_CONCLUIDAS(P_DIAS IN NUMBER) IS
    BEGIN
        DELETE FROM PETRO.TB_PETRO_TODO
        WHERE ST_STATUS = 2
          AND DT_VENCIMENTO < (SYSDATE - P_DIAS);
    END PRC_LIMPAR_CONCLUIDAS;
END PKG_TODO_RULES;
/

INSERT INTO PETRO.TB_PETRO_AREA (CD_AREA, DS_NOME) VALUES (PETRO.SEQ_PETRO_AREA.NEXTVAL, 'Operacoes Offshore');
INSERT INTO PETRO.TB_PETRO_AREA (CD_AREA, DS_NOME) VALUES (PETRO.SEQ_PETRO_AREA.NEXTVAL, 'Refino');
COMMIT;